update
update

diff --git a/bin/barchti-update b/bin/barchti-update
--- a/bin/barchti-update
+++ b/bin/barchti-update
@@ -2,7 +2,7 @@
 
 set -e
 
-trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://barchti.org/discord\033[0m"' ERR
+trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://omarchy.org/discord\033[0m"' ERR
 
 if [[ $1 == "-y" ]] || barchti-update-confirm; then
   barchti-snapshot create || (( $? == 127 ))
